const mongoose = require("mongoose");
const productSchema = mongoose.Schema({
  prpertyType: { type: Array, required: true },
  Negotable: { type: Array },
  price: { type: Number },
  ownership: { type: Array },
  PropertyAge: { type: Array },
  PropertyApproved: { type: Array },
  ProperyDescription: { type: String },
  BankLoan: { type: Array },
  length: { type: Number },
  bredth: { type: Number },
  totalArea: { type: Number, required: true },
  areaUnit: { type: Array },
  noOfBhk: { type: Array },
  noOfFloor: { type: Array },
  attached: { type: Array },
  westernToilet: { type: Array },
  furnished: { type: Array },
  carParking: { type: Array },
  lift: { type: Array },
  electricity: { type: String },
  facing: { type: Array },
  name: { type: Array },
  mobile: { type: Number, required: true },
  postedBy: { type: Array },
  saleType: { type: Array },
  featuredPackage: { type: Array },
  ppdPackage: { type: Array },
  image: { type: String },
  email: { type: String },
  city: { type: Array },
  area: { type: Array },
  pincode: { type: Array },
  address: { type: String },
  landmark: { type: String },
  lattitude: { type: String },
  longitude: { type: String },
  views: { type: Number },
  status: { type: String },
  dayleft: { type: Number }
});
module.exports = mongoose.model("Properties", productSchema);
